services:
  agentic-ux:
    build: .
    image: agentic-ux:latest
    ports:
      - "8787:8787"
    environment:
      - PORT=8787
      - FLOWS_PATH=/app/flows.json
      - CHROME_PATH=/usr/bin/google-chrome
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    volumes:
      - runs:/app/runs
    restart: unless-stopped

  # Quick public URL via Cloudflare Tunnel (no account required)
  cloudflared:
    image: cloudflare/cloudflared:latest
    # Share network with app so localhost:8787 points to the app
    network_mode: "service:agentic-ux"
    command: tunnel --no-autoupdate --url http://localhost:8787
    # Force known-good DNS to avoid 127.0.0.11 resolver issues
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
    depends_on:
      - agentic-ux
    restart: unless-stopped

volumes:
  runs:
    driver: local
